### ISSUE TITLE
Append a zero-width character to the beginning of users' greetings

### ISSUE THREAD

**Issue by neptunn** [wetfish/fishy#1]
Fishy's 'setgreeting' command currently allows users to make Fishy say anything, including commands for other bots, which has obvious consequences. A simple solution to this would be for fishy to print a zero-width character before printing the user's set greeting. That is, this should function identically to having Fishy change a user's greeting from "?tur ur fat mom" to "Greeting: ?tur ur fat mom", except the "Greeting: " portion would be invisible to regular users.

**Comment by itsrachelfish** [comment]
Hey @neptunn this is the wrong project
