### ISSUE TITLE
fishy kb's denice when biggerrainbow is used

### ISSUE THREAD

**Issue by le1ca** [wetfish/fishy#9]
20:04 < lq> !biggerrainbow the best internet on the internet
20:04 < denice>                                                                              
20:04 < denice>    ▄    █                    █                      ▄             ▀          
20:04 < denice>  ▄▄█▄▄  █ ▄▄    ▄▄▄          █▄▄▄    ▄▄▄    ▄▄▄   ▄▄█▄▄         ▄▄▄    ▄ ▄▄  
20:04 < denice>    █    █▀  █  █▀  █         █▀ ▀█  █▀  █  █   ▀    █             █    █▀  █ 
20:04 < denice>    █    █   █  █▀▀▀▀         █   █  █▀▀▀▀   ▀▀▀▄    █             █    █   █ 
20:04 < denice>    ▀▄▄  █   █  ▀█▄▄▀         ██▄█▀  ▀█▄▄▀  ▀▄▄▄▀    ▀▄▄         ▄▄█▄▄  █   █ 
20:04 < denice>                                                                              
20:04 < denice>                                                                              
20:04 < denice>                                                                              
20:04 < denice>    ▄                                  ▄                                  ▄   
20:04 < denice>  ▄▄█▄▄   ▄▄▄    ▄ ▄▄  ▄ ▄▄    ▄▄▄   ▄▄█▄▄          ▄▄▄   ▄ ▄▄          ▄▄█▄▄ 
20:04 < denice>    █    █▀  █   █▀  ▀ █▀  █  █▀  █    █           █▀ ▀█  █▀  █           █   
20:04 < denice>    █    █▀▀▀▀   █     █   █  █▀▀▀▀    █           █   █  █   █           █   
20:04 < denice>    ▀▄▄  ▀█▄▄▀   █     █   █  ▀█▄▄▀    ▀▄▄         ▀█▄█▀  █   █           ▀▄▄ 
20:04 < denice>                                                                              
20:04 < denice>                                                                              
20:04 < denice>                                                                              
20:04 < denice>  █                      ▀             ▄                                  ▄   
20:04 < denice>  █ ▄▄    ▄▄▄          ▄▄▄    ▄ ▄▄   ▄▄█▄▄   ▄▄▄    ▄ ▄▄  ▄ ▄▄    ▄▄▄   ▄▄█▄▄ 
20:04 < denice>  █▀  █  █▀  █           █    █▀  █    █    █▀  █   █▀  ▀ █▀  █  █▀  █    █   
20:04 < denice>  █   █  █▀▀▀▀           █    █   █    █    █▀▀▀▀   █     █   █  █▀▀▀▀    █   
20:04 < denice>  █   █  ▀█▄▄▀         ▄▄█▄▄  █   █    ▀▄▄  ▀█▄▄▀   █     █   █  ▀█▄▄▀    ▀▄▄ 
20:04 < denice>                                                                              
20:04 < denice>                                                                              
20:04 -!- mode/#wetfish [+b *!testbot@Fish-6u2bas.calho.st] by fishy
20:04 -!- denice was kicked from #wetfish by fishy [You've been kicked for violating the triplicates rule! :D]

**Comment by itsrachelfish** [comment]
@le1ca please register denice with services for automatic +h

:wink:
